sudo: required
services: 
  - docker

before_install:
  - docker build -t whiteboii/docker-angular -f Dockerfile.dev .

script: 
  - docker run whiteboii/docker-angular ng test --browsers ChromeCustom --watch=false

# https://hackernoon.com/running-karma-tests-with-headless-chrome-inside-docker-ae4aceb06ed3