sudo: required
services: 
  - docker

before_install:
  - docker build -t whiteboii/docker-angular -f Dockerfile.dev .

script: 
  - docker run whiteboii/docker-angular ng test --browsers ChromeCustom --watch=false

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-angular"
  env: "DockerAngular-env"
  bucket_name: "elasticbeanstalk-eu-central-1-254461019615"
  bucket_path: "docker-angular"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"